package com.example.qrazy.qrazyapplication;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.example.qrazy.qrazyapplication.SearchRecord;
import com.example.qrazy.qrazyapplication.Student;

import com.example.qrazy.qrazyapplication.SearchRecordDao;
import com.example.qrazy.qrazyapplication.StudentDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig searchRecordDaoConfig;
    private final DaoConfig studentDaoConfig;

    private final SearchRecordDao searchRecordDao;
    private final StudentDao studentDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        searchRecordDaoConfig = daoConfigMap.get(SearchRecordDao.class).clone();
        searchRecordDaoConfig.initIdentityScope(type);

        studentDaoConfig = daoConfigMap.get(StudentDao.class).clone();
        studentDaoConfig.initIdentityScope(type);

        searchRecordDao = new SearchRecordDao(searchRecordDaoConfig, this);
        studentDao = new StudentDao(studentDaoConfig, this);

        registerDao(SearchRecord.class, searchRecordDao);
        registerDao(Student.class, studentDao);
    }
    
    public void clear() {
        searchRecordDaoConfig.clearIdentityScope();
        studentDaoConfig.clearIdentityScope();
    }

    public SearchRecordDao getSearchRecordDao() {
        return searchRecordDao;
    }

    public StudentDao getStudentDao() {
        return studentDao;
    }

}
